name: user_repository
description: User Repository Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.35.6"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  user_api:
    path: ../user_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
