name: omni_remote
description: Application to send and receive data from Arduino and ESP boards using a broker and custom MQTT topics.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.35.6"

dependencies:
  bloc: ^9.1.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.0
  google_fonts: ^6.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hugeicons: ^1.1.2
  intl: ^0.20.2
  mqtt_client: ^10.11.3
  user_api:
    path: packages/user_api
  user_api_remote:
    path: packages/user_api_remote
  user_repository:
    path: packages/user_repository
  uuid: ^4.5.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
  mocktail: ^1.0.4
  test_coverage_badge: ^0.3.2
  very_good_analysis: ^10.0.0

flutter_launcher_icons:
  android: true
  image_path_android: "assets/images/app-main-logo-rounded.png"
  adaptive_icon_background: "#145EB9"
  adaptive_icon_foreground: "assets/images/app-main-logo-rounded.png"
  ios: true
  image_path_ios: "assets/images/app-main-logo-rounded.png"
  remove_alpha_ios: true
  background_color_ios: "#145EB9"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
