name: omni_remote
description: Application to send and receive data from Arduino and ESP boards using a broker and custom MQTT topics.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.35.6"

dependencies:
  bloc: ^9.2.0                        # | Android | iOS | Linux | macOS | web | Windows
  equatable: ^2.0.8                   # | Android | iOS | Linux | macOS | web | Windows
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1                # | Android | iOS | Linux | macOS | web | Windows
  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.0                      # | Android | iOS | Linux | macOS | web | Windows
  go_router: ^17.1.0                  # | Android | iOS | Linux | macOS | web | Windows
  google_fonts: ^8.0.2                # | Android | iOS | Linux | macOS | web | Windows
  hive: ^2.2.3                        # | Android | iOS | Linux | macOS | web | Windows
  hive_flutter: ^1.1.0                # | Android | iOS | Linux | macOS | web | Windows
  hugeicons: ^1.1.5                   # | Android | iOS | Linux | macOS | web | Windows
  intl: ^0.20.2                       # | Android | iOS | Linux | macOS | web | Windows
  mqtt_client: ^10.11.9               # | Android | iOS | Linux | macOS | web | Windows
  package_info_plus: ^9.0.0           # | Android | iOS | Linux | macOS | web | Windows
  uuid: ^4.5.2                        # | Android | iOS | Linux | macOS | web | Windows

dev_dependencies:
  bloc_test: ^10.0.0                  # | Android | iOS | Linux | macOS | web | Windows
  flutter_launcher_icons: ^0.14.4     # | Android | iOS | Linux | macOS | web | Windows
  flutter_test:
    sdk: flutter
  mockito: ^5.6.3                     # | Android | iOS | Linux | macOS | web | Windows
  mocktail: ^1.0.4                    # | Android | iOS | Linux | macOS | web | Windows
  very_good_analysis: ^10.2.0         # | Android | iOS | Linux | macOS | web | Windows

flutter_launcher_icons:
  android: true
  image_path_android: "assets/images/app-main-logo-rounded.png"
  adaptive_icon_background: "#145EB9"
  adaptive_icon_foreground: "assets/images/app-main-logo-rounded.png"
  ios: true
  image_path_ios: "assets/images/app-main-logo-rounded.png"
  remove_alpha_ios: true
  background_color_ios: "#145EB9"
  web:
    generate: true
    image_path: "assets/images/logo-web.png"
    background_color: "transparent"
  windows:
   generate: true
   image_path: "assets/images/logo-windows.png"
   icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/logo-macos.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
