name: user_api_remote
description: User API Remote Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  user_api:
    path: ../user_api
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
