name: user_api
description: User API Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
