name: Production
# CI workflow for Omni Remote application.
# This workflow checks the commit author, runs semantic checks, spell checks,
# executes tests, builds the application, and deploys it to the Play Store
# on the 'main' branch. The application is deployed to the Android production track.

concurrency:
  group: main-$-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  semantic-pull-request:
    name: "ðŸ“ Semantic"
    if: github.event_name != 'workflow_dispatch'
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
    permissions:
      contents: read

  spell-check:
    name: "ðŸ” Spell Check"
    if: github.event_name != 'workflow_dispatch'
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false

  tests:
    name: "ðŸ§ª Run Tests"
    if: github.event_name != 'workflow_dispatch'
    needs: [semantic-pull-request, spell-check]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ðŸ“š Git Checkout
        uses: actions/checkout@v6
      - name: ðŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: ðŸ“¦ Install Dependencies
        run: |
          flutter pub get
      - name: âœ¨ Format Check
        run: |
          dart format --set-exit-if-changed .
      - name: ðŸ§ Analyze
        run: |
          flutter analyze
      - name: ðŸ§ª Run Tests
        run: |
          flutter test --coverage
      - name: ðŸ“Š Codecov Badge
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: "ðŸ”¨ Build Application"
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      APP_PACKAGE_NAME: com.pmorales.omni.remote
      AAB_PATH: build/app/outputs/bundle/productionRelease/app-production-release.aab
      KEYSTORE_PATH: android/keystore.jks
      KEY_PROPS_PATH: android/key.properties
      SERVICE_ACCOUNT_PATH: service-account.json
    steps:
      - name: ðŸ“š Git Checkout
        uses: actions/checkout@v6
      - name: ðŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: ðŸ”‘ Decode Android Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > ${{ env.KEYSTORE_PATH }}
      - name: ðŸ”‘ Decode Android Key Properties
        run: echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" | base64 --decode > ${{ env.KEY_PROPS_PATH }}
      - name: ðŸ”‘ Decode Service Account
        run: echo "${{ secrets.ANDROID_RELEASE_SERVICE_ACCOUNT }}" | base64 --decode > ${{ env.SERVICE_ACCOUNT_PATH }}

      - name: ðŸ“¦ Install Dependencies
        run: |
          flutter pub get
      - name: ðŸ› ï¸ Build the application (AAB)
        run: |
          flutter build appbundle --flavor production -t lib/main.dart

      - name: â¬‡ï¸ Upload AAB to Artifacts
        uses: actions/upload-artifact@master
        with:
          name: aab-stores
          path: ${{ env.AAB_PATH }}

  deploy:
    name: "ðŸš€ Deploy to Play Store"
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    env:
      APP_PACKAGE_NAME: com.pmorales.omni.remote
      AAB_PATH: build/app/outputs/bundle/productionRelease/app-production-release.aab
      SERVICE_ACCOUNT_PATH: service-account.json
    steps:
      - name: ðŸ“š Checkout repo
        uses: actions/checkout@v6
      - name: â¬‡ï¸ Download Artifact
        uses: actions/download-artifact@master
        with:
          name: aab-stores
          path: ./downloaded
      - name: ðŸ“ Crear estructura de directorios
        run: |
          mkdir -p build/app/outputs/bundle/productionRelease/
          cp ./downloaded/* build/app/outputs/bundle/productionRelease/
          ls -la build/app/outputs/bundle/productionRelease/
      - name: ðŸ”‘ Decode Service Account
        run: echo "${{ secrets.ANDROID_RELEASE_SERVICE_ACCOUNT }}" | base64 --decode > ${{ env.SERVICE_ACCOUNT_PATH }}          
      - name: ðŸš€ Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ env.SERVICE_ACCOUNT_PATH }}
          packageName: ${{ env.APP_PACKAGE_NAME }}
          releaseFiles: ${{ env.AAB_PATH }}
          whatsNewDirectory: whatsnew
